version: 0.2

environment_variables:
    plaintext:
        HUGO_VERSION: "0.120.4"

phases:
    install:
        commands:
            - cd /tmp
            - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
            - tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
            - mv hugo /usr/bin/hugo
            - cd -
            - rm -rf /tmp/*
            - git submodule init
            - git submodule update
    build:
        commands:
            - rm -rf public
            - hugo
            - hugo deploy
    post_build:
        commands:
            - echo Build completed on `date`